### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by AndssY** [liamhebert/FedFormer#3]
Sincerely thank you for providing such a valuable code, but there seems to be some bugs when I trying to run this code.

First, In `env_utils.py`, I notice `from gym.spaces import Box, Discrete, Tuple` while `gymnaisum` package is used, so it will raise error like this `raise TypeError("Unknown space: {}".format(space))`.

Second, in line 27 of `base.py`, `actions = self.get_actions(obs_np[None])` now return a `tuple` , so there would be a typerror, `TypeError: tuple indices must be integers or slices, not NoneType`. Maybe it can be simply fixed as `actions = self.get_actions(obs_np[0][None])` .

After fixed above all, I try to run `python main.py  --task=reach-v2 --agents=1`, while there is a mistake:
```
Traceback (most recent call last):
  File "/home/andssy/Desktop/FedFormer/main.py", line 213, in <module>
    main()
  File "/home/andssy/miniconda3/envs/Fed/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/andssy/miniconda3/envs/Fed/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/andssy/miniconda3/envs/Fed/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andssy/miniconda3/envs/Fed/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/andssy/Desktop/FedFormer/main.py", line 210, in main
    experiment(variant)
  File "/home/andssy/Desktop/FedFormer/main.py", line 164, in experiment
    algorithm.train()
  File "/home/andssy/Desktop/FedFormer/fed_algorithm.py", line 24, in train
    algorithm.step(epoch)
  File "/home/andssy/Desktop/FedFormer/sac_algorithm.py", line 84, in step
    self._step(epoch, offline_rl)
  File "/home/andssy/Desktop/FedFormer/sac_algorithm.py", line 90, in _step
    init_expl_paths = self.expl_data_collector.collect_new_paths(
  File "/home/andssy/Desktop/FedFormer/fed_path_collector.py", line 53, in collect_new_paths
    path = self._rollout_fn(
  File "/home/andssy/Desktop/FedFormer/rlkit/samplers/rollout_functions.py", line 114, in rollout
    next_o, r, done, env_info = env.step(copy.deepcopy(a))
  File "/home/andssy/Desktop/FedFormer/rlkit/envs/wrappers/normalized_box_env.py", line 55, in step
    next_obs, reward, done, info = wrapped_step
ValueError: too many values to unpack (expected 4)

```
Can you provide us with the appropriate hyperparameters and the correct running command that can reproduce the results of the paper, as I don't have much experience in this area yet.
Thank you again for your contributions to academia and look forward to your work on these issues.

**Comment by liamhebert** [comment]
Hi @AndssY ! Thanks for reading our paper and checking out our codebase. Can you please check whether you are running the latest version of the code? The issue you mentioned in `env_utils.py` was fixed with a patch I pushed last week, see https://github.com/liamhebert/FedFormer/blob/6c2918a6294946dd8019df91dca2ca5969411a1c/rlkit/envs/env_utils.py#L3 (the change to gymnasium from MetaWorld was a headache!). Let me know once you've updated to the latest version whether the issues still persist.

**Comment by liamhebert** [comment]
As for the hyper-parameters, all the ones we used are listed in Table 1 of the paper, with the only difference being the number of agents and the seeds (1 - 10) used between runs.

**Comment by AndssY** [comment]
:+1: :+1: :+1: ：)Thanks for quick reply! The errors encountered above have been successfully resolved!
